//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fast")]
        public global::Vido.AnimationSpeed AnimationSpeed {
            get {
                return ((global::Vido.AnimationSpeed)(this["AnimationSpeed"]));
            }
            set {
                this["AnimationSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShiftKey")]
        public global::Vido.KeyBinding KeyBinding_GoThroughZoomModes {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_GoThroughZoomModes"]));
            }
            set {
                this["KeyBinding_GoThroughZoomModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Return")]
        public global::Vido.KeyBinding KeyBinding_ToggleFullscreen {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_ToggleFullscreen"]));
            }
            set {
                this["KeyBinding_ToggleFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::Vido.KeyBinding KeyBinding_OpenSettings {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_OpenSettings"]));
            }
            set {
                this["KeyBinding_OpenSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::Vido.KeyBinding KeyBinding_LeaveFullscreen {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_LeaveFullscreen"]));
            }
            set {
                this["KeyBinding_LeaveFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+Up")]
        public global::Vido.KeyBinding KeyBinding_ZoomIn {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_ZoomIn"]));
            }
            set {
                this["KeyBinding_ZoomIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+Down")]
        public global::Vido.KeyBinding KeyBinding_ZoomOut {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_ZoomOut"]));
            }
            set {
                this["KeyBinding_ZoomOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Vido.KeyBinding KeyBinding_Left {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_Left"]));
            }
            set {
                this["KeyBinding_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Vido.KeyBinding KeyBinding_Up {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_Up"]));
            }
            set {
                this["KeyBinding_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Vido.KeyBinding KeyBinding_Right {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_Right"]));
            }
            set {
                this["KeyBinding_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Vido.KeyBinding KeyBinding_Down {
            get {
                return ((global::Vido.KeyBinding)(this["KeyBinding_Down"]));
            }
            set {
                this["KeyBinding_Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28, 28, 28")]
        public global::System.Drawing.Color Color_ImageArea {
            get {
                return ((global::System.Drawing.Color)(this["Color_ImageArea"]));
            }
            set {
                this["Color_ImageArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color Color_ControlBar {
            get {
                return ((global::System.Drawing.Color)(this["Color_ControlBar"]));
            }
            set {
                this["Color_ControlBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomImagePath_ZoomButton {
            get {
                return ((string)(this["CustomImagePath_ZoomButton"]));
            }
            set {
                this["CustomImagePath_ZoomButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomImagePath_PreviousButton {
            get {
                return ((string)(this["CustomImagePath_PreviousButton"]));
            }
            set {
                this["CustomImagePath_PreviousButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomImagePath_FullscreenButton {
            get {
                return ((string)(this["CustomImagePath_FullscreenButton"]));
            }
            set {
                this["CustomImagePath_FullscreenButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomImagePath_NextButton {
            get {
                return ((string)(this["CustomImagePath_NextButton"]));
            }
            set {
                this["CustomImagePath_NextButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomImagePath_SettingsButton {
            get {
                return ((string)(this["CustomImagePath_SettingsButton"]));
            }
            set {
                this["CustomImagePath_SettingsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoZoomImageToTopLeft {
            get {
                return ((bool)(this["AutoZoomImageToTopLeft"]));
            }
            set {
                this["AutoZoomImageToTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTooltips {
            get {
                return ((bool)(this["ShowTooltips"]));
            }
            set {
                this["ShowTooltips"] = value;
            }
        }
    }
}
